// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TokDCereja_back_end.Data;

#nullable disable

namespace TokDCereja_back_end.Migrations
{
    [DbContext(typeof(TokDCerejaDbContext))]
    [Migration("20240629162045_UpdateControllers1.0")]
    partial class UpdateControllers10
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TokDCereja_back_end.Models.Agenda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCompromisso")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Agendas");
                });

            modelBuilder.Entity("TokDCereja_back_end.Models.Aprendizado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Categoria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Conteudo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataPublicacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Aprendizados");
                });

            modelBuilder.Entity("TokDCereja_back_end.Models.Caixa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("CapitalDeGiro")
                        .HasColumnType("real");

                    b.Property<float>("CustoFixo")
                        .HasColumnType("real");

                    b.Property<float>("CustoUnidade")
                        .HasColumnType("real");

                    b.Property<DateTime>("DataUltimaAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FerramentaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("FundoReserva")
                        .HasColumnType("real");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<float>("TotalVenda")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Caixas");
                });

            modelBuilder.Entity("TokDCereja_back_end.Models.Estoque", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataUltimaAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ingrediente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Medida")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuantidadeAtual")
                        .HasColumnType("int");

                    b.Property<int>("QuantidadeMax")
                        .HasColumnType("int");

                    b.Property<int>("QuantidadeMin")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Estoques");
                });

            modelBuilder.Entity("TokDCereja_back_end.Models.Feedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Avaliacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataFeedback")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("TokDCereja_back_end.Models.FormaDePagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Banco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CPF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NomeTitular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroParcelas")
                        .HasColumnType("int");

                    b.Property<string>("TipoPagamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoPlano")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<float>("Valor")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("FormasDePagamentos");
                });

            modelBuilder.Entity("TokDCereja_back_end.Models.Plano", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Planos");
                });

            modelBuilder.Entity("TokDCereja_back_end.Models.Precificacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("CustoFixoUnitario")
                        .HasColumnType("real");

                    b.Property<float>("CustoReceita")
                        .HasColumnType("real");

                    b.Property<float>("CustoVariavelUnitario")
                        .HasColumnType("real");

                    b.Property<Guid>("FerramentaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<float>("MaoDeObra")
                        .HasColumnType("real");

                    b.Property<float>("Margemlucro")
                        .HasColumnType("real");

                    b.Property<float>("PrecoVenda")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Precificacoes");
                });

            modelBuilder.Entity("TokDCereja_back_end.Models.TabelaNutricional", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Carboidrato")
                        .HasColumnType("real");

                    b.Property<DateTime>("DataFabricacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataValidade")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FerramentaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("GorduraSaturada")
                        .HasColumnType("real");

                    b.Property<float>("GorduraTotal")
                        .HasColumnType("real");

                    b.Property<float>("Gramas")
                        .HasColumnType("real");

                    b.Property<string>("NomeReceita")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Porcao")
                        .HasColumnType("real");

                    b.Property<float>("Proteina")
                        .HasColumnType("real");

                    b.Property<float>("Quantidade")
                        .HasColumnType("real");

                    b.Property<float>("Sodio")
                        .HasColumnType("real");

                    b.Property<string>("TipoProdutoFinal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("ValorEnergetico")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("TabelasNutricionais");
                });

            modelBuilder.Entity("TokDCereja_back_end.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("FeedbackId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PlanoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Senha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoCadastro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoPlano")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FeedbackId");

                    b.HasIndex("PlanoId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("TokDCereja_back_end.Models.VitrineVirtual", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoriaProduto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FerramentaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImagemProduto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NomeProduto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PlanoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("VitrinesVirtuais");
                });

            modelBuilder.Entity("TokDCereja_back_end.Models.Usuario", b =>
                {
                    b.HasOne("TokDCereja_back_end.Models.Feedback", null)
                        .WithMany("Usuarios")
                        .HasForeignKey("FeedbackId");

                    b.HasOne("TokDCereja_back_end.Models.Plano", "Plano")
                        .WithMany("Usuarios")
                        .HasForeignKey("PlanoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Plano");
                });

            modelBuilder.Entity("TokDCereja_back_end.Models.Feedback", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("TokDCereja_back_end.Models.Plano", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
